## Better Beta Fama-MacBeth

### Import Packages

In [79]:
import pandas as pd
import numpy as np
import datetime as dt
import psycopg2 
import matplotlib.pyplot as plt
from dateutil.relativedelta import *
from pandas.tseries.offsets import *
from scipy import stats
import statsmodels.api as sm
import statistics
import pickle
import sys
sys.path.insert(0, "../")
import util
from importlib import reload
util=reload(util)

### Read in util.py Function Bank

In [80]:
from IPython.lib.backgroundjobs import BackgroundJobFunc

with open('util.py') as code:
    job = BackgroundJobFunc(exec, code.read())

result = job.run()

### Import Data

#### Better Beta Permlist

In [81]:
betterbetadf = pd.read_csv('permlist_better_beta.csv.gz', compression='gzip', usecols=lambda x: x.lower())

betterbetadf['jdate'] = pd.to_datetime(betterbetadf['jdate'])

betterbetadf.head()

,permno,jdate,month,year,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag
0,10001,2011-12-31,12,2011,0.015311,0.000047,0.198816,0.191367,-0.007449,0
1,10001,2012-12-31,12,2012,0.008042,0.000011,0.168342,0.177603,0.009261,1
2,10001,2014-12-31,12,2014,0.007163,0.000010,0.195414,0.214663,0.019250,1
3,10001,2016-12-31,12,2016,0.008193,0.000009,0.130659,0.233114,0.102455,1
4,10002,2002-12-31,12,2002,0.019160,0.000068,0.185383,0.150805,-0.034578,0

In [82]:
betterbetadf.permno.nunique()

11234

In [83]:
betterbetadf.shape

(93000, 10)

In [84]:
# Beta stats after looking at historical outliers
betterbetadf.win_beta.describe()

count    92897.000000
mean         0.950574
std          0.482317
min        -27.817775
25%          0.625067
50%          0.937868
75%          1.252717
max          5.691886
Name: win_beta, dtype: float64

In [85]:
# Beta stats after looking at historical outliers
betterbetadf.normal_beta.describe()

count    92897.000000
mean         0.984740
std          1.875747
min       -222.785789
25%          0.582259
50%          0.943591
75%          1.322680
max        216.287619
Name: normal_beta, dtype: float64

In [86]:
betterbetadf.head()

,permno,jdate,month,year,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag
0,10001,2011-12-31,12,2011,0.015311,0.000047,0.198816,0.191367,-0.007449,0
1,10001,2012-12-31,12,2012,0.008042,0.000011,0.168342,0.177603,0.009261,1
2,10001,2014-12-31,12,2014,0.007163,0.000010,0.195414,0.214663,0.019250,1
3,10001,2016-12-31,12,2016,0.008193,0.000009,0.130659,0.233114,0.102455,1
4,10002,2002-12-31,12,2002,0.019160,0.000068,0.185383,0.150805,-0.034578,0

### Annualized Returns

In [154]:
AnnRet = pd.read_csv('AnnRet.csv.gz', compression='gzip', usecols=lambda x: x.lower())

AnnRet['jdate'] = pd.to_datetime(AnnRet['jdate'])

AnnRet['annRetadj'] = AnnRet['annRet']-0.05

#drop and rename
betterbetadf.drop(columns=['month','year'],inplace=True)

AnnRet.head()

# from these files, already have top 3k by market share every december
# permno already mapped to permco
# just need to merge, lag, split by quantile and regress

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,dlstdt,retadj,retxadj,month,year,1+retadj,annRet,daycount,annRet10,annRetadj
0,10001,7953,0.000000,0.000000,1054.0,-9.500,11.0,3.0,1986-01-09,1993-11-21,...,NaN,0.000000,0.000000,12,1990,1.000000,-0.009264,365,-0.009264,-0.059264
1,10001,7953,-0.025210,-0.025210,1075.0,14.500,11.0,3.0,1986-01-09,1993-11-21,...,NaN,-0.025210,-0.025210,12,1991,0.974790,0.607307,365,0.650747,0.557307
2,10001,7953,-0.017544,-0.017544,1080.0,14.000,11.0,3.0,1986-01-09,1993-11-21,...,NaN,-0.017544,-0.017544,12,1992,0.982456,0.013423,366,0.013423,-0.036577
3,10001,7953,-0.006757,-0.006757,1091.0,-18.375,11.0,3.0,1993-11-22,2004-06-09,...,NaN,-0.006757,-0.006757,12,1993,0.993243,0.371066,365,0.323788,0.321066
4,10001,7953,-0.030303,-0.030303,2224.0,8.000,11.0,3.0,1993-11-22,2004-06-09,...,NaN,-0.030303,-0.030303,12,1994,0.969697,-0.090405,364,-0.064961,-0.140405

In [88]:
AnnRet.permno.nunique()

16896

In [155]:
AnnRet.annRetadj.describe()

count    157372.000000
mean          0.108568
std           0.928094
min          -1.050000
25%          -0.296303
50%          -0.008310
75%           0.302369
max          95.755678
Name: annRetadj, dtype: float64

**Should be around 10%...**

In [89]:
# Clean up pre-merge
betterbetadf.drop(columns=['month','year'],inplace=True)

betterbetadf.permno.nunique()

11234

In [151]:
crsp = AnnRet.merge(betterbetadf,how='inner',on=['permno','jdate'])

In [152]:
crsp.permno.nunique()

10880

In [153]:
crsp.annRet.describe()

count    69000.000000
mean         0.269621
std          1.042828
min         -0.992727
25%         -0.136127
50%          0.117383
75%          0.420218
max         95.805678
Name: annRet, dtype: float64

In [106]:
crsp.head()

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,1+retadj,annRet,daycount,annRet10,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag
0,10001,7953,0.012809,0.012809,8157.0,9.33,11.0,2.0,2010-07-09,2017-08-03,...,1.012809,-0.139629,366,-0.132028,0.008042,0.000011,0.168342,0.177603,0.009261,1
1,10001,7953,0.006393,0.006393,10488.0,11.02,11.0,2.0,2010-07-09,2017-08-03,...,1.006393,0.444209,365,0.272996,0.007163,0.000010,0.195414,0.214663,0.019250,1
2,10002,7954,0.019284,0.019284,8729.0,11.10,11.0,3.0,2002-05-15,2004-06-09,...,1.019284,0.172122,365,0.159229,0.019160,0.000068,0.185383,0.150805,-0.034578,0
3,10002,7954,0.014427,0.014427,11021.0,24.61,11.0,3.0,2004-06-10,2006-06-29,...,1.014427,0.578713,366,0.581674,0.007018,0.000069,1.394708,1.530405,0.135697,1
4,10002,7954,0.005568,0.005568,17497.0,12.10,11.0,3.0,2006-06-30,2013-02-15,...,1.005568,-0.511157,365,-0.486615,0.010070,0.000103,1.013144,1.103796,0.090653,1

In [107]:
crsp = util.lag(crsp,'beta_delta')

crsp.permno.nunique()

10880

In [108]:
crsp[crsp['permno']==70519].head()

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,annRet,daycount,annRet10,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag,lagbeta_delta
31027,70519,20483,0.016667,0.016667,108162.0,22.875,11.0,1.0,1989-01-20,1994-01-02,...,-0.185677,365,-0.213282,0.010047,0.000128,1.272366,1.324268,0.051903,1,NaN
31028,70519,20483,0.003185,0.003185,108185.0,39.375,11.0,1.0,1989-01-20,1994-01-02,...,0.747234,365,0.827106,0.009007,0.000106,1.302269,1.296749,-0.005520,0,0.051903
31029,70519,20483,-0.007692,-0.007692,109829.0,48.375,11.0,1.0,1989-01-20,1994-01-02,...,0.250353,366,0.258343,0.006100,0.000053,1.433195,1.460942,0.027748,1,-0.005520
31030,70519,20483,0.023026,0.023026,242067.0,38.875,11.0,1.0,1989-01-20,1994-01-02,...,0.629590,365,0.592555,0.005418,0.000046,1.579891,1.899938,0.320047,1,0.027748
31031,70519,20483,-0.042216,-0.042216,638937.0,45.375,11.0,1.0,1995-04-27,1998-10-07,...,0.468668,366,0.562216,0.007421,0.000091,1.645572,1.655849,0.010277,1,0.320047

In [109]:
crsp.dtypes

permno                       int64
permco                       int64
ret                        float64
retx                       float64
shrout                     float64
prc                        float64
shrcd                      float64
exchcd                     float64
namedt                      object
nameendt                    object
jdate               datetime64[ns]
dlret                      float64
dlstdt                      object
retadj                     float64
retxadj                    float64
month                        int64
year                         int64
1+retadj                   float64
annRet                     float64
daycount                     int64
annRet10                   float64
mktSD                      float64
covmktstock                float64
win_beta                   float64
normal_beta                float64
beta_delta                 float64
better_beta_flag             int64
lagbeta_delta              float64
dtype: object

In [110]:
crsp['me'] = crsp['shrout'] * crsp['prc']

crsp[['permno', 'jdate', 'shrout', 'prc', 'me']].head()

    permno      jdate   shrout     prc          me
6    10010 1990-12-31   6999.0   9.750   68240.250
9    10016 1990-12-31  13599.0  13.750  186986.250
17   10019 1990-12-31   5473.0   6.500   35574.500
18   10020 1990-12-31  20450.0  11.250  230062.500
21   10025 1990-12-31   4775.0   7.875   37603.125

In [111]:
crsp.permno.nunique()

10880

In [117]:
crsp = crsp.dropna(subset = ['lagbeta_delta'])

crsp.permno.nunique()

8762

In [118]:
# Pick top xxxx based on market cap per jdate, which is annual now
#crsp = util.topX(crsp, 'me', 2000)

def topX(dfinput, tsig,nstocks):
    df=dfinput.copy()
    #rank all stocks based on signal 'tsig', e.g. market cap or beta etc at given time
    df[tsig+'Rank']=df.groupby(['jdate'])[tsig].rank(ascending=False)
    #drop all stocks higher rank than that signal value 
    df.drop(df.loc[df[tsig+'Rank']>nstocks].index,inplace=True)
    df=df.drop([tsig+'Rank'],axis=1)
    return df

df=crsp.copy()
#rank all stocks based on signal 'tsig', e.g. market cap or beta etc at given time
df['me_Rank']=df.groupby(['jdate', 'permno'])['me'].rank(ascending=False)
df = df.sort_values(['jdate', 'me_Rank'], ascending=[True, True])
#drop all stocks higher rank than that signal value 
#df.drop(df.loc[df['me'+'Rank']>3000],inplace=True)
#df=df.drop([tsig+'Rank'],axis=1)

df[['permno', 'jdate', 'me', 'me_Rank', 'lagbeta_delta', 'annRet']].head(50)

In [119]:
crsp.permno.nunique()

8762

In [120]:
crsp.head()

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,daycount,annRet10,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag,lagbeta_delta,me
7,10010,7967,0.056075,0.056075,7567.0,14.125,11.0,3.0,1986-01-17,1995-08-28,...,365,0.486843,0.009007,0.000094,1.160623,1.344205,0.183582,1,0.316021,106883.875
10,10016,1728,0.019231,0.019231,13594.0,13.250,11.0,3.0,1986-12-29,1998-05-25,...,365,-0.021573,0.009007,0.000026,0.323056,-0.046250,-0.369306,0,-0.075472,180120.500
19,10020,7972,0.000000,0.000000,24045.0,14.500,11.0,3.0,1986-01-27,1993-04-30,...,365,0.484974,0.009007,0.000012,0.142520,0.022488,-0.120032,0,-0.042655,348652.500
22,10025,7975,0.098039,0.098039,4816.0,14.000,11.0,3.0,1986-01-30,2004-06-09,...,365,0.696973,0.009007,0.000048,0.594238,0.360280,-0.233959,0,-0.204983,67424.000
40,10026,7976,0.036364,0.036364,10659.0,14.250,11.0,3.0,1986-02-04,2000-07-31,...,365,0.753849,0.009007,0.000075,0.922334,0.801563,-0.120770,0,-0.074072,151890.750

In [121]:
# Review of Citi = 70519
crsp[crsp['permno']==70519]

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,daycount,annRet10,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag,lagbeta_delta,me
31028,70519,20483,0.003185,0.003185,108185.0,39.3750,11.0,1.0,1989-01-20,1994-01-02,...,365,0.827106,0.009007,0.000106,1.302269,1.296749,-0.005520,0,0.051903,4.259784e+06
31029,70519,20483,-0.007692,-0.007692,109829.0,48.3750,11.0,1.0,1989-01-20,1994-01-02,...,366,0.258343,0.006100,0.000053,1.433195,1.460942,0.027748,1,-0.005520,5.312978e+06
31030,70519,20483,0.023026,0.023026,242067.0,38.8750,11.0,1.0,1989-01-20,1994-01-02,...,365,0.592555,0.005418,0.000046,1.579891,1.899938,0.320047,1,0.027748,9.410355e+06
31031,70519,20483,-0.042216,-0.042216,638937.0,45.3750,11.0,1.0,1995-04-27,1998-10-07,...,366,0.562216,0.007421,0.000091,1.645572,1.655849,0.010277,1,0.320047,2.899177e+07
31032,70519,20483,0.002326,0.002326,1144079.0,53.8750,11.0,1.0,1995-04-27,1998-10-07,...,365,0.779052,0.011422,0.000212,1.624196,1.649893,0.025697,1,0.010277,6.163726e+07
31033,70519,20483,-0.017305,-0.017305,2271966.0,49.6875,11.0,1.0,1998-12-04,2000-05-31,...,365,0.052606,0.012780,0.000269,1.647201,1.709825,0.062624,1,0.025697,1.128883e+08
31034,70519,20483,0.006780,0.006780,3371665.0,55.6875,11.0,1.0,1998-12-04,2000-05-31,...,365,0.458601,0.011384,0.000188,1.451721,1.469829,0.018109,1,0.062624,1.877596e+08
31035,70519,20483,-0.013870,-0.013870,5144814.0,50.4800,11.0,1.0,2000-06-01,2002-01-01,...,365,-0.021230,0.013580,0.000249,1.349707,1.355677,0.005969,1,0.018109,2.597102e+08
31036,70519,20483,-0.001702,-0.001702,5056768.0,35.1900,11.0,1.0,2002-02-01,2004-06-09,...,365,-0.232917,0.016396,0.000419,1.556720,1.574067,0.017347,1,0.005969,1.779477e+08
31037,70519,20483,0.002271,0.002271,5158677.0,48.5400,11.0,1.0,2002-02-01,2004-06-09,...,365,0.345432,0.010752,0.000138,1.193491,1.193866,0.000375,1,0.017347,2.504022e+08
31038,70519,20483,0.003123,0.003123,5189753.0,48.1800,11.0,1.0,2004-06-10,2011-05-08,...,366,-0.000564,0.006988,0.000054,1.098484,1.105811,0.007327,1,0.000375,2.500423e+08
31039,70519,20483,0.005121,0.005121,4981134.0,29.4400,11.0,1.0,2004-06-10,2011-05-08,...,365,-0.435639,0.010070,0.000139,1.368054,1.368749,0.000695,1,0.007327,1.466446e+08
31040,70519,20483,-0.013235,-0.013235,5449540.0,6.7100,11.0,1.0,2004-06-10,2011-05-08,...,366,-0.742718,0.025808,0.001198,1.798104,1.950628,0.152524,1,0.000695,3.656641e+07
31041,70519,20483,-0.003012,-0.003012,22863947.0,3.3100,11.0,1.0,2004-06-10,2011-05-08,...,365,-0.508375,0.017188,0.000699,2.366733,2.899770,0.533037,1,0.152524,7.567966e+07
31042,70519,20483,-0.006303,-0.006303,29049600.0,4.7300,11.0,1.0,2004-06-10,2011-05-08,...,365,0.317553,0.011372,0.000181,1.401943,1.443354,0.041411,1,0.533037,1.374046e+08
31043,70519,20483,0.014099,0.014099,2932521.0,39.5600,11.0,1.0,2011-05-09,2014-07-30,...,366,0.362108,0.008042,0.000130,2.002674,2.066169,0.063495,1,0.041411,1.160105e+08
31044,70519,20483,0.003660,0.003660,3033001.0,52.1100,11.0,1.0,2011-05-09,2014-07-30,...,365,0.240587,0.006973,0.000075,1.539035,1.561005,0.021970,1,0.063495,1.580497e+08
31045,70519,20483,-0.013311,-0.013311,3029488.0,54.1100,11.0,1.0,2014-07-31,2015-02-04,...,365,-0.018955,0.007163,0.000063,1.221104,1.246523,0.025420,1,0.021970,1.639256e+08
31046,70519,20483,-0.010516,-0.010516,2978990.0,51.7500,11.0,1.0,2015-02-05,2019-06-23,...,365,0.022094,0.009760,0.000122,1.278624,1.277297,-0.001327,0,0.025420,1.541627e+08
31047,70519,20483,0.004438,0.004438,2442137.0,52.0600,11.0,1.0,2015-02-05,2019-06-23,...,365,-0.293465,0.010742,0.000120,1.037018,1.035904,-0.001114,0,-0.001327,1.271377e+08
31048,70519,20483,0.004779,0.004779,2183194.0,79.8900,11.0,1.0,2019-09-30,2021-09-30,...,365,0.456903,0.007855,0.000092,1.484136,1.482407,-0.001729,0,-0.001114,1.744154e+08
31049,70519,20483,0.013145,0.013145,2081960.0,61.6600,11.0,1.0,2019-09-30,2021-09-30,...,366,-0.198305,0.021690,0.000724,1.538265,1.562075,0.023810,1,-0.001729,1.283737e+08

In [122]:
crsp[crsp['permno']==70519].annRet.describe()

count    22.000000
mean      0.152838
std       0.442933
min      -0.759760
25%      -0.164370
50%       0.144786
75%       0.496303
max       0.798656
Name: annRet, dtype: float64

In [123]:
# ServiceNow Check = 13447
crsp[crsp['permno']==13447].annRet.describe()

count    6.000000
mean     0.542183
std      0.311073
min      0.211397
25%      0.298201
50%      0.475573
75%      0.795258
max      0.949659
Name: annRet, dtype: float64

In [124]:
crsp.annRet.describe()

count    58061.000000
mean         0.245209
std          0.854042
min         -0.992727
25%         -0.126173
50%          0.126475
75%          0.416059
max         37.703760
Name: annRet, dtype: float64

In [125]:
crsp.lagbeta_delta.describe()

count    58061.000000
mean         0.019484
std          0.491939
min        -31.785676
25%         -0.031470
50%          0.000231
75%          0.048924
max         51.462616
Name: lagbeta_delta, dtype: float64

In [131]:
crsp_sorted = crsp.sort_values('lagbeta_delta', ascending=False)

In [132]:
crsp_sorted.head()

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,daycount,annRet10,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag,lagbeta_delta,me
52831,85477,15743,-0.010870,-0.010870,12959.0,12.74,11.0,3.0,2004-06-10,2009-07-09,...,365,0.650255,0.011542,0.000035,0.262594,0.024717,-0.237878,0,51.462616,165097.66
63400,90400,45708,0.045201,0.045201,10028.0,16.88,11.0,3.0,2012-05-02,2013-06-30,...,366,-0.244066,0.008042,0.000084,1.305096,1.522156,0.217060,1,36.839385,169272.64
58829,88368,37737,0.001592,0.001592,16677.0,6.29,11.0,3.0,2006-07-07,2021-09-30,...,366,0.938368,0.008518,0.000063,0.869271,0.872824,0.003552,1,34.275740,104898.33
67552,92456,52874,0.028807,0.028807,70683.0,2.50,11.0,3.0,2008-06-23,2021-09-30,...,365,1.083351,0.006973,0.000052,1.070131,0.621556,-0.448574,0,32.388784,176707.50
55242,86512,16340,0.007792,0.007792,17605.0,7.76,11.0,3.0,1999-07-01,2004-06-09,...,365,0.149238,0.017773,0.000153,0.483456,0.478097,-0.005359,0,22.043021,136614.80

In [133]:
crsp_sorted.permno.nunique()

8762

### Better Beta Regression w/o Quantiles

In [134]:
df_ols = crsp_sorted.copy()

import statsmodels.formula.api as smf

def ols_coef(x,formula):
    return smf.ols(formula,data=x).fit().params

gamma = (df_ols.groupby(['jdate']).apply(ols_coef,'annRet ~ lagbeta_delta'))

def fm_summary(p):
    s = p.describe().T
    s['std_error'] = s['std']/np.sqrt(s['count'])
    s['tstat'] = s['mean']/s['std_error']
    return s[['mean','std_error','tstat']]

fm_summary(gamma)

                   mean  std_error     tstat
Intercept      0.242436   0.054062  4.484374
lagbeta_delta  0.044965   0.042019  1.070110

### Better Beta Regression w/Quantiles

In [135]:
df = crsp_sorted.copy()
#df = returns1.copy()

qsig = 'lagbeta_delta'
#qsig = 'lagstockSD'

nquant = 5
df = util.splitQ(df,qsig,nquant)

df.head()

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag,lagbeta_delta,me,ranklagbeta_delta,lagbeta_deltaq
52831,85477,15743,-0.010870,-0.010870,12959.0,12.74,11.0,3.0,2004-06-10,2009-07-09,...,0.011542,0.000035,0.262594,0.024717,-0.237878,0,51.462616,165097.66,2373.0,4
63400,90400,45708,0.045201,0.045201,10028.0,16.88,11.0,3.0,2012-05-02,2013-06-30,...,0.008042,0.000084,1.305096,1.522156,0.217060,1,36.839385,169272.64,2673.0,4
58829,88368,37737,0.001592,0.001592,16677.0,6.29,11.0,3.0,2006-07-07,2021-09-30,...,0.008518,0.000063,0.869271,0.872824,0.003552,1,34.275740,104898.33,2672.0,4
67552,92456,52874,0.028807,0.028807,70683.0,2.50,11.0,3.0,2008-06-23,2021-09-30,...,0.006973,0.000052,1.070131,0.621556,-0.448574,0,32.388784,176707.50,2780.0,4
55242,86512,16340,0.007792,0.007792,17605.0,7.76,11.0,3.0,1999-07-01,2004-06-09,...,0.017773,0.000153,0.483456,0.478097,-0.005359,0,22.043021,136614.80,2716.0,4

In [137]:
temp = {}

for i in range(nquant):
    dftemp = df[df[qsig+'q']==i]
    import statsmodels.formula.api as smf

    def ols_coef(x,formula):
        return smf.ols(formula,data=x).fit().params

    gamma = (dftemp.groupby(['jdate']).apply(ols_coef,'annRet ~ lagbeta_delta'))

    def fm_summary(p):
        s = p.describe().T
        s['std_error'] = s['std']/np.sqrt(s['count'])
        s['tstat'] = s['mean']/s['std_error']
        return s[['mean','std_error','tstat']]

    temp['q='+str(i)]=fm_summary(gamma)
    
print(str(dftemp.groupby(['jdate'])['permno'].count()[0])+' stocks in each quantile')
for entry in temp:
    print('\n'+entry,'\n',temp[entry])

433 stocks in each quantile

q=0
                    mean  std_error     tstat
Intercept      0.289356   0.061422  4.710942
lagbeta_delta -0.195881   0.055116 -3.553995

q=1
                    mean  std_error     tstat
Intercept      0.141262   0.041001  3.445348
lagbeta_delta -1.586408   0.953013 -1.664624

q=2
                    mean  std_error     tstat
Intercept      0.158505   0.037498  4.227002
lagbeta_delta -1.734411   1.120877 -1.547370

q=3
                    mean  std_error     tstat
Intercept      0.150294   0.044828  3.352714
lagbeta_delta  2.062568   1.059519  1.946702

q=4
                    mean  std_error     tstat
Intercept      0.333310   0.102397  3.255079
lagbeta_delta  0.159282   0.068324  2.331255

In [138]:
dftemp.columns

Index(['permno', 'permco', 'ret', 'retx', 'shrout', 'prc', 'shrcd', 'exchcd',
       'namedt', 'nameendt', 'jdate', 'dlret', 'dlstdt', 'retadj', 'retxadj',
       'month', 'year', '1+retadj', 'annRet', 'daycount', 'annRet10', 'mktSD',
       'covmktstock', 'win_beta', 'normal_beta', 'beta_delta',
       'better_beta_flag', 'lagbeta_delta', 'me', 'ranklagbeta_delta',
       'lagbeta_deltaq'],
      dtype='object')

In [139]:
dftemp.head()

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag,lagbeta_delta,me,ranklagbeta_delta,lagbeta_deltaq
52831,85477,15743,-0.010870,-0.010870,12959.0,12.74,11.0,3.0,2004-06-10,2009-07-09,...,0.011542,0.000035,0.262594,0.024717,-0.237878,0,51.462616,165097.66,2373.0,4
63400,90400,45708,0.045201,0.045201,10028.0,16.88,11.0,3.0,2012-05-02,2013-06-30,...,0.008042,0.000084,1.305096,1.522156,0.217060,1,36.839385,169272.64,2673.0,4
58829,88368,37737,0.001592,0.001592,16677.0,6.29,11.0,3.0,2006-07-07,2021-09-30,...,0.008518,0.000063,0.869271,0.872824,0.003552,1,34.275740,104898.33,2672.0,4
67552,92456,52874,0.028807,0.028807,70683.0,2.50,11.0,3.0,2008-06-23,2021-09-30,...,0.006973,0.000052,1.070131,0.621556,-0.448574,0,32.388784,176707.50,2780.0,4
55242,86512,16340,0.007792,0.007792,17605.0,7.76,11.0,3.0,1999-07-01,2004-06-09,...,0.017773,0.000153,0.483456,0.478097,-0.005359,0,22.043021,136614.80,2716.0,4

In [140]:
dftemp[dftemp['lagbeta_deltaq']==4]

,permno,permco,ret,retx,shrout,prc,shrcd,exchcd,namedt,nameendt,...,mktSD,covmktstock,win_beta,normal_beta,beta_delta,better_beta_flag,lagbeta_delta,me,ranklagbeta_delta,lagbeta_deltaq
52831,85477,15743,-0.010870,-0.010870,12959.0,12.7400,11.0,3.0,2004-06-10,2009-07-09,...,0.011542,0.000035,0.262594,0.024717,-0.237878,0,51.462616,165097.66,2373.0,4
63400,90400,45708,0.045201,0.045201,10028.0,16.8800,11.0,3.0,2012-05-02,2013-06-30,...,0.008042,0.000084,1.305096,1.522156,0.217060,1,36.839385,169272.64,2673.0,4
58829,88368,37737,0.001592,0.001592,16677.0,6.2900,11.0,3.0,2006-07-07,2021-09-30,...,0.008518,0.000063,0.869271,0.872824,0.003552,1,34.275740,104898.33,2672.0,4
67552,92456,52874,0.028807,0.028807,70683.0,2.5000,11.0,3.0,2008-06-23,2021-09-30,...,0.006973,0.000052,1.070131,0.621556,-0.448574,0,32.388784,176707.50,2780.0,4
55242,86512,16340,0.007792,0.007792,17605.0,7.7600,11.0,3.0,1999-07-01,2004-06-09,...,0.017773,0.000153,0.483456,0.478097,-0.005359,0,22.043021,136614.80,2716.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43166,79909,30036,-0.005650,-0.005650,8813.0,22.0000,11.0,1.0,1993-11-03,2001-08-23,...,0.015619,0.000106,0.434596,0.430826,-0.003770,0,0.004417,193886.00,2117.0,4
47961,82857,31581,-0.041667,-0.041667,15012.0,10.0625,11.0,1.0,1996-02-23,1999-01-03,...,0.010983,0.000312,2.582727,1.336471,-1.246256,0,0.004312,151058.25,2116.0,4
22370,47379,2519,0.058333,0.058333,34470.0,31.7500,11.0,3.0,1984-07-02,2004-06-09,...,0.012780,0.000110,0.672929,0.598109,-0.074820,0,0.004302,1094422.50,2115.0,4
27761,61524,20481,0.046512,0.046512,152100.0,16.8750,11.0,1.0,1998-09-01,2002-01-01,...,0.012780,0.000179,1.095143,1.089978,-0.005166,0,0.004255,2566687.50,2114.0,4
30396,68144,21691,-0.041504,-0.041504,209568.0,76.5000,11.0,1.0,1985-07-01,2001-08-23,...,0.012780,0.000169,1.035836,1.044733,0.008896,1,0.004140,16031952.00,2113.0,4

In [149]:
dftemp.annRet.describe()

count    11597.000000
mean         0.359148
std          1.294731
min         -0.980446
25%         -0.231371
50%          0.115472
75%          0.576227
max         37.703760
Name: annRet, dtype: float64

In [141]:
dftemp.to_csv("qFFdata_better_beta.csv.gz", 
           index=False, 
           compression="gzip")

In [142]:
for k in temp.keys():
    print(temp[k])

                   mean  std_error     tstat
Intercept      0.289356   0.061422  4.710942
lagbeta_delta -0.195881   0.055116 -3.553995
                   mean  std_error     tstat
Intercept      0.141262   0.041001  3.445348
lagbeta_delta -1.586408   0.953013 -1.664624
                   mean  std_error     tstat
Intercept      0.158505   0.037498  4.227002
lagbeta_delta -1.734411   1.120877 -1.547370
                   mean  std_error     tstat
Intercept      0.150294   0.044828  3.352714
lagbeta_delta  2.062568   1.059519  1.946702
                   mean  std_error     tstat
Intercept      0.333310   0.102397  3.255079
lagbeta_delta  0.159282   0.068324  2.331255

### Fama-MacBeth Gamma Plot

# Prep data and create beta quantiles

df2 = crsp.copy()
#df = returns1.copy()

qsig = 'lagbeta_delta'
#qsig = 'lagstockSD'

nquant = 5
df2 = util.splitQ(df2,qsig,nquant)

# Start by creating an empty dataframe
coef_table = pd.DataFrame()

for i in range(1991, 2021):
    print("Year: ", i)
    
    # Subset data for each year and the largest quantile
    dftemp2 = df2[(df2.year == i) & (df2.lagbeta_deltaq == 4)]
    
    y = dftemp2[['annRet']]
    X = sm.add_constant(dftemp2[['lagbeta_delta']])
    model_FM = sm.OLS(y,X).fit()
    params = pd.Series(model_FM.params)
    print(i, " ", params)
    coef_table = coef_table.append(params, ignore_index=True)

# Change column names
#coef_table.rename({0: 'Intercept', 1: 'Gamma'}, axis=1, inplace=True)
coef_table['year'] = range(1991, 2021)
print(coef_table)

coef_table.describe()

#### T-Stat of Yearly Signal

# Run T-Test on Coefficients' Time Series
print("Mean: ", coef_table[['lagbeta_delta']].mean())
print("Standard Deviation: ", coef_table[['lagbeta_delta']].std())
print("T: ", coef_table[['lagbeta_delta']].mean()/coef_table[['lagbeta_delta']].std()*(coef_table.shape[0]-1)**(1/2))

#### Plot

plt.plot(coef_table.year, coef_table.lagbeta_delta)
plt.title('Gamma Over Time')
plt.xlabel('Year')
plt.ylabel('Coefficient of Beta')
plt.show()