## Ivo Python Excercise
## Task 2
### Annual Returns

#### Load Packages

In [1]:
import pandas as pd

#### Read in Compressed CSV

In [2]:
df_crsp = pd.read_csv('crsp_a_stock.csv.gz', compression='gzip')

#df_Apple = df_crsp[df_crsp['PERMNO']==14593]

df_crsp.head()

/Users/natejensen/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (7,8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,PERMNO,date,SHRCD,EXCHCD,TICKER,COMNAM,PERMCO,DLRETX,DLRET,PRC,RET,SHROUT,RETX
0,10000,01/06/1986,NaN,NaN,NaN,NaN,7952,NaN,NaN,NaN,NaN,NaN,NaN
1,10000,01/07/1986,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,NaN,-2.5625,C,3680.0,C
2,10000,01/08/1986,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,NaN,-2.5000,-0.024390,3680.0,-0.024390
3,10000,01/09/1986,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,NaN,-2.5000,0.000000,3680.0,0.000000
4,10000,01/10/1986,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,NaN,-2.5000,0.000000,3680.0,0.000000

In [4]:
df_crsp.dtypes

PERMNO      int64
date       object
SHRCD     float64
EXCHCD    float64
TICKER     object
COMNAM     object
PERMCO      int64
DLRETX     object
DLRET      object
PRC       float64
RET        object
SHROUT    float64
RETX       object
dtype: object

#### Calculate Annualized Return

In [5]:
# Fix date format
def jdate(df):
    if 'date' in df.columns:
        df['jdate']=pd.to_datetime(df['date'])
        df.drop(columns=['date'], inplace=True)
    return df

df_crsp=jdate(df_crsp)

In [6]:
# Fix returns format
df_crsp["DLRET"] = pd.to_numeric(df_crsp.DLRET, errors='coerce')
df_crsp["RET"] = pd.to_numeric(df_crsp.RET, errors='coerce')
df_crsp["RETX"] = pd.to_numeric(df_crsp.RETX, errors='coerce')

In [7]:
# Pre-processing of return data
def comebineRet(df):
    #Clear N/A return entries and calculated returns adjusted for the delisting return
    df['DLRET']=df['DLRET'].fillna(0)
    df['RET']=df['RET'].fillna(0)
    df['RETX']=df['RETX'].fillna(0)

    #combine returns
    df['retadj']=(1+df['RET'])*(1+df['DLRET'])-1
    df['retxadj']=(1+df['RETX'])*(1+df['DLRET'])-1
    return df

df_crsp = comebineRet(df_crsp)

df_crsp.head()

,PERMNO,SHRCD,EXCHCD,TICKER,COMNAM,PERMCO,DLRETX,DLRET,PRC,RET,SHROUT,RETX,jdate,retadj,retxadj
0,10000,NaN,NaN,NaN,NaN,7952,NaN,0.0,NaN,0.00000,NaN,0.00000,1986-01-06,0.00000,0.00000
1,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5625,0.00000,3680.0,0.00000,1986-01-07,0.00000,0.00000
2,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5000,-0.02439,3680.0,-0.02439,1986-01-08,-0.02439,-0.02439
3,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5000,0.00000,3680.0,0.00000,1986-01-09,0.00000,0.00000
4,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5000,0.00000,3680.0,0.00000,1986-01-10,0.00000,0.00000

In [8]:
def annRet(df):
    #Create annual return data set
    df=df.sort_values(['PERMNO','jdate'],ascending=[True,True])
    df['jdate'] = pd.to_datetime(df['jdate'])
    df['month'] = df['jdate'].dt.month
    df['year'] = df['jdate'].dt.year
    df['1+retadj']=df['retadj']+1
    df['annRet'] = df.groupby(['PERMNO','year'])['1+retadj'].cumprod()-1
    return df

df_crsp_annRet = annRet(df_crsp)

df_crsp_annRet.head()

,PERMNO,SHRCD,EXCHCD,TICKER,COMNAM,PERMCO,DLRETX,DLRET,PRC,RET,SHROUT,RETX,jdate,retadj,retxadj,month,year,1+retadj,annRet
0,10000,NaN,NaN,NaN,NaN,7952,NaN,0.0,NaN,0.00000,NaN,0.00000,1986-01-06,0.00000,0.00000,1,1986,1.00000,0.00000
1,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5625,0.00000,3680.0,0.00000,1986-01-07,0.00000,0.00000,1,1986,1.00000,0.00000
2,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5000,-0.02439,3680.0,-0.02439,1986-01-08,-0.02439,-0.02439,1,1986,0.97561,-0.02439
3,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5000,0.00000,3680.0,0.00000,1986-01-09,0.00000,0.00000,1,1986,1.00000,-0.02439
4,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.5000,0.00000,3680.0,0.00000,1986-01-10,0.00000,0.00000,1,1986,1.00000,-0.02439

In [9]:
df_crsp_annRet = df_crsp_annRet.drop_duplicates(['PERMNO','year'],keep='last')

In [10]:
df_crsp_annRet.head()

,PERMNO,SHRCD,EXCHCD,TICKER,COMNAM,PERMCO,DLRETX,DLRET,PRC,RET,SHROUT,RETX,jdate,retadj,retxadj,month,year,1+retadj,annRet
250,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-0.51563,0.000000,3843.0,0.000000,1986-12-31,0.000000,0.000000,12,1986,1.000000,-0.798781
363,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,NaN,0.000000,NaN,0.000000,1987-06-12,0.000000,0.000000,6,1987,1.000000,-0.575759
612,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,7.00000,0.056604,991.0,0.056604,1986-12-31,0.056604,0.056604,12,1986,1.056604,0.297045
865,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,5.87500,-0.040816,992.0,-0.040816,1987-12-31,-0.040816,-0.040816,12,1987,0.959184,-0.098984
1118,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,6.37500,-0.019231,998.0,-0.019231,1988-12-30,-0.019231,-0.019231,12,1988,0.980769,0.160856

#### Verify Results

In [11]:
df_Apple_2019 = df_crsp_annRet[(df_crsp_annRet['jdate'].dt.year==2019) & (df_crsp_annRet['PERMNO']==14593)]

df_Apple_2019[['PERMNO', 'year', 'annRet', 'PRC', 'SHROUT']]

         PERMNO  year    annRet        PRC     SHROUT
9299490   14593  2019  0.889663  293.64999  4384959.0

if Apple 2019 checks out then run again for entire set of companies

#### Export Data

In [12]:
df_crsp_annRet_sub = df_crsp_annRet[['PERMNO', 'year', 'annRet', 'PRC', 'SHROUT']]

df_crsp_annRet_sub.to_csv('CRSP_Annual_Returns.csv')

## January Effect

In [16]:
#startyear=1990
startday=10

In [17]:
df_crsp = df_crsp.sort_values('jdate', ascending=True)

In [18]:
df_crsp['daycount'] = df_crsp['jdate'].dt.dayofyear

df_crsp.head()

In [19]:
df_crsp2 = df_crsp.copy()

In [20]:
df_crsp2 = df_crsp2[~(df_crsp2['daycount']<startday)]

In [21]:
#Create annual return data set
df_crsp_annRet2 = annRet(df_crsp2)

df_crsp_annRet2.head()

,PERMNO,SHRCD,EXCHCD,TICKER,COMNAM,PERMCO,DLRETX,DLRET,PRC,RET,SHROUT,RETX,jdate,retadj,retxadj,daycount,month,year,1+retadj,annRet
4,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.500,0.000000,3680.0,0.000000,1986-01-10,0.000000,0.000000,10,1,1986,1.000000,0.00
5,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.625,0.050000,3680.0,0.050000,1986-01-13,0.050000,0.050000,13,1,1986,1.050000,0.05
6,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.750,0.047619,3680.0,0.047619,1986-01-14,0.047619,0.047619,14,1,1986,1.047619,0.10
7,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-2.875,0.045455,3680.0,0.045455,1986-01-15,0.045455,0.045455,15,1,1986,1.045455,0.15
8,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-3.000,0.043478,3680.0,0.043478,1986-01-16,0.043478,0.043478,16,1,1986,1.043478,0.20

In [22]:
df_crsp_annRet2 = df_crsp_annRet2.drop_duplicates(['PERMNO','year'],keep='last')

#### Verify Results

In [23]:
df_Apple2_2019 = df_crsp_annRet2[(df_crsp_annRet2['jdate'].dt.year==2019) & (df_crsp_annRet['PERMNO']==14593)]

df_Apple2_2019[['PERMNO', 'year', 'annRet', 'PRC', 'SHROUT']]

<ipython-input-23-ad65ccc210c4>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_Apple2_2019 = df_crsp_annRet2[(df_crsp_annRet2['jdate'].dt.year==2019) & (df_crsp_annRet['PERMNO']==14593)]

         PERMNO  year    annRet        PRC     SHROUT
9299490   14593  2019  0.944266  293.64999  4384959.0

#### Export Data

In [24]:
df_crsp_annRet2_sub = df_crsp_annRet2[['PERMNO', 'year', 'annRet', 'PRC', 'SHROUT']]

df_crsp_annRet2_sub.to_csv('CRSP_Annual_Returns_Jan_Effect.csv')

## Ivo Python Excercise 
## Task 3
### Firm Size

For each stock-year calculate the marketcap on the last trading day of each calendar year.

Also, calculate the rank of each stock on this last day of the year. (NA if not trading on last day of year)

Save your data as a mcap.csv data set. For example, it may contain lines such as

permno,cusip,ticker,year,yyyymmdd,mktcap,rankmktcap
14593,03783310,AAPL,2018,20181231,746079173,1
93436,88160R10,TSLA,2018,20181231,57441944,103
...
Handcheck some outliers:

For example, which firms had the biggest change in rank from year to year? Does this seem right? Can you handcheck the basics?
Create some test cases, e.g.,

if ( (permno == 93436) and (year == 2018) ) check( rankmktc

In [13]:
df_crsp_annRet.head()

,PERMNO,SHRCD,EXCHCD,TICKER,COMNAM,PERMCO,DLRETX,DLRET,PRC,RET,SHROUT,RETX,jdate,retadj,retxadj,month,year,1+retadj,annRet
250,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-0.51563,0.000000,3843.0,0.000000,1986-12-31,0.000000,0.000000,12,1986,1.000000,-0.798781
363,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,NaN,0.000000,NaN,0.000000,1987-06-12,0.000000,0.000000,6,1987,1.000000,-0.575759
612,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,7.00000,0.056604,991.0,0.056604,1986-12-31,0.056604,0.056604,12,1986,1.056604,0.297045
865,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,5.87500,-0.040816,992.0,-0.040816,1987-12-31,-0.040816,-0.040816,12,1987,0.959184,-0.098984
1118,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,6.37500,-0.019231,998.0,-0.019231,1988-12-30,-0.019231,-0.019231,12,1988,0.980769,0.160856

In [14]:
df_crsp_annRet['Firm_Size'] = df_crsp_annRet['PRC']*df_crsp_annRet['SHROUT']

df_crsp_annRet.head()

,PERMNO,SHRCD,EXCHCD,TICKER,COMNAM,PERMCO,DLRETX,DLRET,PRC,RET,SHROUT,RETX,jdate,retadj,retxadj,month,year,1+retadj,annRet,Firm_Size
250,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,-0.51563,0.000000,3843.0,0.000000,1986-12-31,0.000000,0.000000,12,1986,1.000000,-0.798781,-1981.56609
363,10000,10.0,3.0,OMFGA,OPTIMUM MANUFACTURING INC,7952,NaN,0.0,NaN,0.000000,NaN,0.000000,1987-06-12,0.000000,0.000000,6,1987,1.000000,-0.575759,NaN
612,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,7.00000,0.056604,991.0,0.056604,1986-12-31,0.056604,0.056604,12,1986,1.056604,0.297045,6937.00000
865,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,5.87500,-0.040816,992.0,-0.040816,1987-12-31,-0.040816,-0.040816,12,1987,0.959184,-0.098984,5828.00000
1118,10001,11.0,3.0,GFGC,GREAT FALLS GAS CO,7953,NaN,0.0,6.37500,-0.019231,998.0,-0.019231,1988-12-30,-0.019231,-0.019231,12,1988,0.980769,0.160856,6362.25000

In [18]:
df_firm_size = df_crsp_annRet.copy()

df_firm_size = df_firm_size.sort_values(by=["year","Firm_Size"], ascending=False)
df_firm_size["rank"] = df.groupby("year")["Firm_Size"].rank("dense", ascending=False)
df_firm_size[['year', 'PERMNO', 'TICKER', 'Firm_Size', 'rank']].head(20)

          year  PERMNO TICKER     Firm_Size  rank
9299743   2020   14593   AAPL  2.255969e+09   1.0
302747    2020   10107   MSFT  1.681606e+09   2.0
64539535  2020   84788   AMZN  1.634168e+09   3.0
81975981  2020   93436   TSLA  6.689053e+08   4.0
7489451   2020   13407     FB  6.566682e+08   5.0
9224084   2020   14542   GOOG  5.778874e+08   6.0
75212847  2020   90319  GOOGL  5.269207e+08   7.0
15586946  2020   22111    JNJ  4.143096e+08   8.0
33075183  2020   55976    WMT  4.078415e+08   9.0
28404669  2020   47896    JPM  3.873352e+08  10.0
80350902  2020   92611      V  3.708954e+08  11.0
77351954  2020   91233     MA  3.528245e+08  12.0
13340297  2020   18163     PG  3.450124e+08  13.0
80415296  2020   92655    UNH  3.327325e+08  14.0
63958958  2020   84398    SPY  3.314379e+08  15.0
17967124  2020   26403    DIS  3.280237e+08  16.0
67908603  2020   86580   NVDA  3.232418e+08  17.0
61990876  2020   83443    BRK  3.178826e+08  18.0
39669281  2020   66181     HD  2.859668e+08  19.0
10570029  2020   15488   PYPL  2.744103e+08  20.0

#### Verify Results

In [19]:
df_mcap_Apple = df_firm_size[df_firm_size['PERMNO']==14593]

df_mcap_Apple[['PERMNO', 'year', 'Firm_Size', 'rank']]

         PERMNO  year     Firm_Size    rank
9299743   14593  2020  2.255969e+09     1.0
9299490   14593  2019  1.287643e+09     1.0
9299238   14593  2018  7.460792e+08     2.0
9298987   14593  2017  8.608825e+08     1.0
9298736   14593  2016  6.089602e+08     1.0
9298484   14593  2015  5.836127e+08     1.0
9298232   14593  2014  6.431201e+08     1.0
9297980   14593  2013  5.006806e+08     1.0
9297728   14593  2012  4.996960e+08     1.0
9297478   14593  2011  3.775467e+08     2.0
9297226   14593  2010  2.970890e+08     2.0
9296974   14593  2009  1.909826e+08     4.0
9296722   14593  2008  7.599692e+07    26.0
9296469   14593  2007  1.740388e+08    10.0
9296218   14593  2006  7.298106e+07    41.0
9295967   14593  2005  6.079141e+07    45.0
9295715   14593  2004  2.605296e+07   109.0
9295463   14593  2003  7.880423e+06   328.0
9295211   14593  2002  5.162483e+06   366.0
9294959   14593  2001  7.718852e+06   305.0
9294711   14593  2000  5.136442e+06   472.0
9294459   14593  1999  1.656916e+07   170.0
9294207   14593  1998  5.584571e+06   372.0
9293955   14593  1997  1.680249e+06   931.0
9293702   14593  1996  2.600712e+06   562.0
9293448   14593  1995  3.924386e+06   332.0
9293196   14593  1994  4.675710e+06   203.0
9292944   14593  1993  3.407479e+06   304.0
9292691   14593  1992  7.041000e+06   119.0
9292437   14593  1991  6.679874e+06   112.0
9292184   14593  1990  4.915502e+06   123.0
9291931   14593  1989  4.413370e+06   157.0
9291679   14593  1988  4.958357e+06   104.0
9291426   14593  1987  5.215476e+06    86.0
9291173   14593  1986  2.541416e+06   218.0
9290920   14593  1985  1.370358e+06   339.0
9290667   14593  1984  1.768586e+06   205.0
9290414   14593  1983  1.448119e+06   250.0
9290161   14593  1982  1.722234e+06   163.0
9289908   14593  1981 -1.229653e+06  5431.0
9289655   14593  1980 -1.884962e+06  5050.0

#### Export Data

In [20]:
df_firm_size = df_firm_size[['PERMNO', 'TICKER', 'year', 'Firm_Size', 'PRC', 'SHROUT', 'rank']]

df_firm_size.to_csv('Market_Cap.csv')